name: Build SunamoEnumsHelper

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoEnumsHelper
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoEnumsHelper/SunamoEnumsHelper.csproj

    - name: Build
      run: dotnet build SunamoEnumsHelper/SunamoEnumsHelper.csproj --configuration Release --no-restore

  test:
    name: Test SunamoEnumsHelper.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoEnumsHelper.Tests/SunamoEnumsHelper.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoEnumsHelper.Tests/SunamoEnumsHelper.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoEnumsHelper.Tests/SunamoEnumsHelper.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
